"""F4 follow-up: _project(entry) must equal serialize.to_jsonable(entry)
today, and this test is the trigger to notice the day they stop agreeing.

The module docstring explains why canonical_json owns its own projection
(_project) instead of calling leakproof.serialize.to_jsonable: an unrelated
future change to that function's _DERIVED table could otherwise silently
change a hash already committed to disk. That decoupling (commit
760650b, "fix(audit): own the canonical-JSON projection instead of
delegating") landed one commit before tests/fixtures/audit/golden.jsonl was
generated (commit 8572ad1). Had the two projections actually differed at
that point, the golden fixture would simply have been generated against
whichever one canonical_json used at the time, and nothing in the diff, the
tests, or the report would have said so -- the divergence would have been
permanently invisible.

Importing serialize here (in a test) is fine and does not undo F4: the
point of F4 is that the *hash path* (canonical_json, _project) must not
import or depend on serialize, not that this test suite may never look at
both at once. If this test ever fails because the two are deliberately
allowed to diverge, the golden fixture must be regenerated by hand at the
same time -- treat a failure here as that trigger, not as a bug to relax
away."""

from __future__ import annotations

from datetime import date

from leakproof import serialize
from leakproof.audit import _project
from leakproof.contract import AuditAction, State
from leakproof.types import AuditEntry


def test_project_matches_to_jsonable_today():
    entry = AuditEntry(
        seq=1,
        prev_hash="0" * 64,
        hash="deadbeef",
        ts="2026-08-21T09:00:00Z",
        as_of=date(2026, 8, 21),
        actor="ops",
        action=AuditAction.APPROVE,
        exception_id="e-100",
        state_before=State.CLAIM_READY,
        state_after=State.CLAIM_READY,
        amount_paise=150000,
        artifact_path="packs/e-100.json",
    )
    assert _project(entry) == serialize.to_jsonable(entry)


def test_project_matches_to_jsonable_with_none_fields():
    """The all-None-optional-fields shape (a bare ingest entry) is worth
    pinning separately: None round-trips differently in principle (e.g. a
    derived-field table could inject a default), so both branches deserve
    their own check rather than only ever exercising the fully-populated
    case above."""
    entry = AuditEntry(
        seq=1,
        prev_hash="0" * 64,
        hash="deadbeef",
        ts="2026-08-21T09:00:00Z",
        as_of=date(2026, 8, 21),
        actor="ops",
        action=AuditAction.INGEST,
        exception_id=None,
        state_before=None,
        state_after=None,
        amount_paise=None,
        artifact_path=None,
    )
    assert _project(entry) == serialize.to_jsonable(entry)
